Updated spanish translation
sokratis12GR/ArmorPlus pull request #106
Opened 2017-02-12 12:17 UTC by KewaiiGamer

2017-03-07 15:34 UTC, sokratis12GR commented on src/main/resources/assets/armorplus/lang/es_ES.lang
> +#CONSOLE LOG -- As part of console output, these entries shall not be translated. --
@KewaiiGamer this part is no longer used and would be best if it is removed

2017-06-24 20:13 UTC, elifoster requested changes

2017-06-24 20:13 UTC, elifoster commented on src/main/resources/assets/armorplus/lang/es_ES.lang
> +item.armorplus.emerald_bow.name=Arco de Esmeralda
Shouldn't this be `Arco Esmeralda` or the other emerald things be `Cosa de Esmeralda`?

2017-06-24 20:13 UTC, elifoster commented on src/main/resources/assets/armorplus/lang/es_ES.lang
> +item.armorplus.ender_dragon_arrow.name=Flecha del Dragon del End
`Dragon` -> `Dragón`

2017-06-24 20:13 UTC, elifoster commented on src/main/resources/assets/armorplus/lang/es_ES.lang
> +item.armorplus.ender_dragon_bow.name=Arco del Dragon del End
`Dragon` -> `Dragón`

2017-06-24 20:13 UTC, elifoster commented on src/main/resources/assets/armorplus/lang/es_ES.lang
> +item.armorplus.ender_dragon_battle_axe.name=Hacha de Batalla del Dragon del End
`Dragon` -> `Dragón`

2017-06-24 20:13 UTC, elifoster commented on src/main/resources/assets/armorplus/lang/es_ES.lang
> +item.armorplus.ender_dragon_sword.name=Espada del Dragon del End
`Dragon` -> `Dragón`

2017-08-03 07:30 UTC, sokratis12GR commented
Okay, so soon (within a few days/hours) I'm going to merge this and modify the files with the given suggestions and changes.

2017-08-03 08:01 UTC, merged